// @refresh reset
import { createContext, useContext, useState } from "react";

const TRANSLATIONS = {
  en: {
    name: "English",
    flag: "🇺🇸",
    // Sidebar
    chat: "Chat",
    checkin: "Check-in",
    study: "Study",
    music: "Music",
    trends: "Trends",
    journal: "Journal",
    calendar: "Calendar",
    report: "Report",
    settings: "Settings",
    // Dashboard / general
    good_morning: "Good morning",
    good_afternoon: "Good afternoon",
    good_evening: "Good evening",
    // Daily Logs
    daily_checkin: "Daily Check-in",
    how_today: "How are you doing today?",
    mood: "Mood",
    stress: "Stress",
    sleep: "Sleep (hrs)",
    exercise: "Exercise (min)",
    water: "Water (glasses)",
    notes_placeholder: "Anything on your mind? (optional)",
    log_today: "Log today",
    saving: "Saving...",
    already_logged: "Already logged today",
    come_back: "Come back tomorrow 💙",
    todays_goals: "Today's goals",
    companion_says: "Your companion says",
    // Study
    study_timer: "Study Timer",
    focus_rest: "Focus, then rest.",
    subject: "Subject",
    subject_placeholder: "e.g. Biology, Math, History...",
    duration: "Duration",
    start_session: "Start session",
    starting: "Starting...",
    end_early: "End early",
    stay_focused: "Stay focused — you've got this",
    focus_rating: "Focus rating",
    energy_level: "Energy level",
    scattered: "Scattered",
    locked_in: "Locked in",
    drained: "Drained",
    energized: "Energized",
    notes_optional: "Any notes? (optional)",
    save_finish: "Save & finish",
    session_complete: "Session complete!",
    great_work: "Great work. Take a well-earned break.",
    start_another: "Start another",
    min: "min",
    // Music
    music_mood: "Music for your mood",
    music_desc: "Tell me how you feel — I'll generate music just for you.",
    quick_moods: "Quick moods",
    describe_yourself: "Or describe it yourself",
    music_placeholder: "e.g. I'm feeling overwhelmed with exams, I want something soft and calming...",
    generate_music: "Generate music",
    composing: "Composing...",
    composing_music: "Composing your music...",
    now_playing: "Now playing · 30s",
    paused: "Paused",
    generate_another: "Generate another version",
    calm_focused: "Calm & focused",
    stressed: "Stressed",
    motivated: "Motivated",
    anxious: "Anxious",
    happy: "Happy",
    tired: "Tired",
    // Trends
    trends_title: "Trends",
    wellness_patterns: "Your wellness patterns over time",
    stability: "Stability",
    streaks: "Streaks",
    weekly: "weekly",
    monthly: "monthly",
    avg_mood: "Avg Mood",
    avg_sleep: "Avg Sleep",
    avg_stress: "Avg Stress",
    no_data: "No data yet",
    start_logging: "Start logging daily to see trends",
    loading: "Loading...",
    // Journal
    journal_title: "Journal",
    // Calendar
    calendar_title: "Calendar",
    // Settings
    settings_title: "Settings",
    customize: "Customize your experience",
    your_companion: "Your companion",
    account: "Account",
    signed_in_as: "Signed in as",
    sign_out: "Sign out",
    companion_switched: "✓ Companion switched!",
    calm_grounding: "Calm, grounding, steady",
    warm_expressive: "Warm, expressive, uplifting",
    // Login
    welcome_back: "Welcome back",
    login_subtitle: "Sign in to continue with your companion",
    email: "Email",
    password: "Password",
    sign_in: "Sign in",
    signing_in: "Signing in...",
    no_account: "Don't have an account?",
    sign_up: "Sign up",
    // Chat
    how_feeling: "How are you feeling today? Tap the mic to talk to me, or type below. 💙",
    tap_connect: "tap mic to connect",
    listening: "listening...",
    speaking: "speaking...",
    voice: "Voice",
    text: "Text",
    tap_start: "Tap to start talking to",
    is_speaking: "is speaking...",
    is_listening: "is listening — speak now",
    message_placeholder: "Message",
  },

  es: {
    name: "Español",
    flag: "🇪🇸",
    chat: "Chat",
    checkin: "Check-in",
    study: "Estudiar",
    music: "Música",
    trends: "Tendencias",
    journal: "Diario",
    calendar: "Calendario",
    report: "Reporte",
    settings: "Ajustes",
    good_morning: "Buenos días",
    good_afternoon: "Buenas tardes",
    good_evening: "Buenas noches",
    daily_checkin: "Check-in Diario",
    how_today: "¿Cómo te encuentras hoy?",
    mood: "Estado de ánimo",
    stress: "Estrés",
    sleep: "Sueño (horas)",
    exercise: "Ejercicio (min)",
    water: "Agua (vasos)",
    notes_placeholder: "¿Algo en mente? (opcional)",
    log_today: "Registrar hoy",
    saving: "Guardando...",
    already_logged: "Ya registraste hoy",
    come_back: "Vuelve mañana 💙",
    todays_goals: "Objetivos de hoy",
    companion_says: "Tu compañero dice",
    study_timer: "Temporizador de estudio",
    focus_rest: "Enfócate, luego descansa.",
    subject: "Materia",
    subject_placeholder: "ej. Biología, Matemáticas, Historia...",
    duration: "Duración",
    start_session: "Iniciar sesión",
    starting: "Iniciando...",
    end_early: "Terminar antes",
    stay_focused: "Mantén el enfoque — tú puedes",
    focus_rating: "Nivel de concentración",
    energy_level: "Nivel de energía",
    scattered: "Disperso",
    locked_in: "Concentrado",
    drained: "Agotado",
    energized: "Energizado",
    notes_optional: "¿Alguna nota? (opcional)",
    save_finish: "Guardar y terminar",
    session_complete: "¡Sesión completada!",
    great_work: "Buen trabajo. Tómate un descanso.",
    start_another: "Comenzar otra",
    min: "min",
    music_mood: "Música para tu estado de ánimo",
    music_desc: "Dime cómo te sientes — generaré música solo para ti.",
    quick_moods: "Estados rápidos",
    describe_yourself: "O descríbelo tú mismo",
    music_placeholder: "ej. Me siento abrumado con los exámenes, quiero algo suave y tranquilo...",
    generate_music: "Generar música",
    composing: "Componiendo...",
    composing_music: "Componiendo tu música...",
    now_playing: "Reproduciendo · 30s",
    paused: "Pausado",
    generate_another: "Generar otra versión",
    calm_focused: "Calmado y enfocado",
    stressed: "Estresado",
    motivated: "Motivado",
    anxious: "Ansioso",
    happy: "Feliz",
    tired: "Cansado",
    trends_title: "Tendencias",
    wellness_patterns: "Tus patrones de bienestar en el tiempo",
    stability: "Estabilidad",
    streaks: "Rachas",
    weekly: "semanal",
    monthly: "mensual",
    avg_mood: "Ánimo Prom.",
    avg_sleep: "Sueño Prom.",
    avg_stress: "Estrés Prom.",
    no_data: "Sin datos aún",
    start_logging: "Empieza a registrar diariamente para ver tendencias",
    loading: "Cargando...",
    journal_title: "Diario",
    calendar_title: "Calendario",
    settings_title: "Ajustes",
    customize: "Personaliza tu experiencia",
    your_companion: "Tu compañero",
    account: "Cuenta",
    signed_in_as: "Conectado como",
    sign_out: "Cerrar sesión",
    companion_switched: "✓ ¡Compañero cambiado!",
    calm_grounding: "Calmado, sereno, estable",
    warm_expressive: "Cálido, expresivo, animado",
    welcome_back: "Bienvenido de vuelta",
    login_subtitle: "Inicia sesión para continuar con tu compañero",
    email: "Correo electrónico",
    password: "Contraseña",
    sign_in: "Iniciar sesión",
    signing_in: "Iniciando sesión...",
    no_account: "¿No tienes cuenta?",
    sign_up: "Regístrate",
    how_feeling: "¿Cómo te sientes hoy? Toca el micrófono para hablar conmigo, o escribe abajo. 💙",
    tap_connect: "toca el mic para conectar",
    listening: "escuchando...",
    speaking: "hablando...",
    voice: "Voz",
    text: "Texto",
    tap_start: "Toca para hablar con",
    is_speaking: "está hablando...",
    is_listening: "está escuchando — habla ahora",
    message_placeholder: "Mensaje",
  },

  fr: {
    name: "Français",
    flag: "🇫🇷",
    chat: "Chat",
    checkin: "Check-in",
    study: "Étudier",
    music: "Musique",
    trends: "Tendances",
    journal: "Journal",
    calendar: "Calendrier",
    report: "Rapport", 
    settings: "Paramètres",
    good_morning: "Bonjour",
    good_afternoon: "Bon après-midi",
    good_evening: "Bonsoir",
    daily_checkin: "Check-in Quotidien",
    how_today: "Comment vous sentez-vous aujourd'hui ?",
    mood: "Humeur",
    stress: "Stress",
    sleep: "Sommeil (h)",
    exercise: "Exercice (min)",
    water: "Eau (verres)",
    notes_placeholder: "Quelque chose en tête ? (optionnel)",
    log_today: "Enregistrer aujourd'hui",
    saving: "Enregistrement...",
    already_logged: "Déjà enregistré aujourd'hui",
    come_back: "Reviens demain 💙",
    todays_goals: "Objectifs du jour",
    companion_says: "Votre compagnon dit",
    study_timer: "Minuteur d'étude",
    focus_rest: "Concentrez-vous, puis reposez-vous.",
    subject: "Matière",
    subject_placeholder: "ex. Biologie, Maths, Histoire...",
    duration: "Durée",
    start_session: "Démarrer la session",
    starting: "Démarrage...",
    end_early: "Terminer plus tôt",
    stay_focused: "Restez concentré — vous y arrivez",
    focus_rating: "Niveau de concentration",
    energy_level: "Niveau d'énergie",
    scattered: "Dispersé",
    locked_in: "Concentré",
    drained: "Épuisé",
    energized: "Énergisé",
    notes_optional: "Des notes ? (optionnel)",
    save_finish: "Sauvegarder et terminer",
    session_complete: "Session terminée !",
    great_work: "Bon travail. Prenez une pause bien méritée.",
    start_another: "Commencer une autre",
    min: "min",
    music_mood: "Musique pour votre humeur",
    music_desc: "Dites-moi ce que vous ressentez — je générerai de la musique rien que pour vous.",
    quick_moods: "Humeurs rapides",
    describe_yourself: "Ou décrivez-le vous-même",
    music_placeholder: "ex. Je me sens dépassé par les examens, je veux quelque chose de doux et apaisant...",
    generate_music: "Générer de la musique",
    composing: "Composition...",
    composing_music: "Composition de votre musique...",
    now_playing: "En cours · 30s",
    paused: "En pause",
    generate_another: "Générer une autre version",
    calm_focused: "Calme et concentré",
    stressed: "Stressé",
    motivated: "Motivé",
    anxious: "Anxieux",
    happy: "Heureux",
    tired: "Fatigué",
    trends_title: "Tendances",
    wellness_patterns: "Vos habitudes de bien-être au fil du temps",
    stability: "Stabilité",
    streaks: "Séries",
    weekly: "hebdomadaire",
    monthly: "mensuel",
    avg_mood: "Humeur Moy.",
    avg_sleep: "Sommeil Moy.",
    avg_stress: "Stress Moy.",
    no_data: "Pas encore de données",
    start_logging: "Commencez à enregistrer quotidiennement pour voir les tendances",
    loading: "Chargement...",
    journal_title: "Journal",
    calendar_title: "Calendrier",
    settings_title: "Paramètres",
    customize: "Personnalisez votre expérience",
    your_companion: "Votre compagnon",
    account: "Compte",
    signed_in_as: "Connecté en tant que",
    sign_out: "Se déconnecter",
    companion_switched: "✓ Compagnon changé !",
    calm_grounding: "Calme, ancré, stable",
    warm_expressive: "Chaleureux, expressif, stimulant",
    welcome_back: "Bon retour",
    login_subtitle: "Connectez-vous pour continuer avec votre compagnon",
    email: "Email",
    password: "Mot de passe",
    sign_in: "Se connecter",
    signing_in: "Connexion...",
    no_account: "Pas encore de compte ?",
    sign_up: "S'inscrire",
    how_feeling: "Comment vous sentez-vous aujourd'hui ? Appuyez sur le micro pour me parler, ou écrivez ci-dessous. 💙",
    tap_connect: "appuyez sur le micro pour connecter",
    listening: "à l'écoute...",
    speaking: "en train de parler...",
    voice: "Voix",
    text: "Texte",
    tap_start: "Appuyez pour parler à",
    is_speaking: "parle...",
    is_listening: "écoute — parlez maintenant",
    message_placeholder: "Message",
  },

  zh: {
    name: "中文",
    flag: "🇨🇳",
    chat: "聊天",
    checkin: "每日记录",
    study: "学习",
    music: "音乐",
    trends: "趋势",
    journal: "日记",
    calendar: "日历",
    report: "报告",
    settings: "设置",
    good_morning: "早上好",
    good_afternoon: "下午好",
    good_evening: "晚上好",
    daily_checkin: "每日签到",
    how_today: "你今天感觉怎么样？",
    mood: "情绪",
    stress: "压力",
    sleep: "睡眠（小时）",
    exercise: "运动（分钟）",
    water: "喝水（杯）",
    notes_placeholder: "有什么想说的吗？（可选）",
    log_today: "记录今天",
    saving: "保存中...",
    already_logged: "今天已经记录过了",
    come_back: "明天再来 💙",
    todays_goals: "今日目标",
    companion_says: "你的伙伴说",
    study_timer: "学习计时器",
    focus_rest: "专注学习，然后休息。",
    subject: "科目",
    subject_placeholder: "例如：生物、数学、历史...",
    duration: "时长",
    start_session: "开始学习",
    starting: "正在开始...",
    end_early: "提前结束",
    stay_focused: "保持专注——你可以的",
    focus_rating: "专注度",
    energy_level: "精力水平",
    scattered: "分散",
    locked_in: "专注",
    drained: "疲惫",
    energized: "充沛",
    notes_optional: "有备注吗？（可选）",
    save_finish: "保存并完成",
    session_complete: "学习完成！",
    great_work: "做得很好。好好休息一下。",
    start_another: "再开始一次",
    min: "分钟",
    music_mood: "适合你心情的音乐",
    music_desc: "告诉我你的感受——我会为你生成专属音乐。",
    quick_moods: "快速心情",
    describe_yourself: "或者自己描述",
    music_placeholder: "例如：我感到被考试压垮了，想要一些轻柔平静的音乐...",
    generate_music: "生成音乐",
    composing: "创作中...",
    composing_music: "正在为你创作音乐...",
    now_playing: "正在播放 · 30秒",
    paused: "已暂停",
    generate_another: "生成另一个版本",
    calm_focused: "平静专注",
    stressed: "压力大",
    motivated: "充满动力",
    anxious: "焦虑",
    happy: "开心",
    tired: "疲惫",
    trends_title: "趋势",
    wellness_patterns: "你的健康模式随时间变化",
    stability: "稳定性",
    streaks: "连续记录",
    weekly: "每周",
    monthly: "每月",
    avg_mood: "平均情绪",
    avg_sleep: "平均睡眠",
    avg_stress: "平均压力",
    no_data: "暂无数据",
    start_logging: "开始每日记录以查看趋势",
    loading: "加载中...",
    journal_title: "日记",
    calendar_title: "日历",
    settings_title: "设置",
    customize: "个性化你的体验",
    your_companion: "你的伙伴",
    account: "账户",
    signed_in_as: "当前登录为",
    sign_out: "退出登录",
    companion_switched: "✓ 伙伴已切换！",
    calm_grounding: "平静、稳定、踏实",
    warm_expressive: "温暖、表达丰富、鼓励人心",
    welcome_back: "欢迎回来",
    login_subtitle: "登录以继续与你的伙伴互动",
    email: "邮箱",
    password: "密码",
    sign_in: "登录",
    signing_in: "登录中...",
    no_account: "还没有账户？",
    sign_up: "注册",
    how_feeling: "你今天感觉怎么样？点击麦克风和我说话，或在下方输入。 💙",
    tap_connect: "点击麦克风连接",
    listening: "正在聆听...",
    speaking: "正在说话...",
    voice: "语音",
    text: "文字",
    tap_start: "点击开始与",
    is_speaking: "正在说话...",
    is_listening: "正在聆听——请说话",
    message_placeholder: "消息",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  const switchLang = (code) => {
    setLang(code);
    localStorage.setItem("lang", code);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS["en"]?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t, languages: TRANSLATIONS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}